'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

    '''<summary>
    '''PnlIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlIP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LblNamaPeserta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNamaPeserta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblIdPeserta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIdPeserta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNamaKaryawan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNamaKaryawan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTglLahir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTglLahir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblJnsKelamin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblJnsKelamin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblPerusahaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPerusahaan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNoPol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNoPol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblBelakusampai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBelakusampai As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PnlNonIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlNonIP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LblNoPesertaBPJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNoPesertaBPJS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNamaPeserta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNamaPeserta1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblIdPeserta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIdPeserta1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaskes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaskes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTglLahir1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTglLahir1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblPerusahaan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPerusahaan1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblKelasRawat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblKelasRawat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNoPol1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNoPol1 As Global.System.Web.UI.WebControls.Label
End Class
