'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PolicyMemberExcess

    '''<summary>
    '''PnlPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlPolicy As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLPolicy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PnlMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtKeyWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKeyWord As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GVVw_Claim_Info_Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVVw_Claim_Info_Header As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LinkClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkClose As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LblPeserta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPeserta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblRelasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRelasi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblPOLIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPOLIS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMemID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblClientNm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblClientNm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBirthDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNIK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNIK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblAccNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAccNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GVClaim_Info_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVClaim_Info_Detail As Global.System.Web.UI.WebControls.GridView
End Class
